version: '3'
services:
    tor-obfs4-bridge:
        container_name: tor-obfs4-bridge
        environment:
            - OR_PORT=42218
            - PT_PORT=51000
            - CONTACT_INFO=admin@optional.com
        ports:
            - '42218:42218'
            - '51000:51000'
            - '9150:9150'
        volumes:
            - './tor_obfs4_bridge_data:/var/lib/tor'
        tmpfs: '/tmp:rw,size=4k'
        image: ookangzheng/docker-tor-obfs-bridge:latest
